"use client";

import { useEffect, useState } from 'react';
import { useLanguage } from '@/context/LanguageContext';

export const publicTranslationMap: Record<string, string> = {
  "Magia": "Magic",
  "Instalar": "Install",
  "Magic": "magic",
  "Ahora no": "Not now",
  "Descubre la": "Discover the",
  "Instalar VamosJuntos": "Install Let's Go Together",
  "Explora tu": "Explore your",
  "Discover the": "Discover the",
  "Explore Your": "Explore Your",
  "Acceso rápido desde tu pantalla": "Quick access from your screen",
  "ticket": "ticket",
  "Gastronomía": "Gastronomy",
  "Diseña tu Experiencia": "Design your Experience",
  "No hay taxis disponibles": "No taxis available",
  "No has seleccionado servicios aún.": "You have not selected services yet.",
  "Tu Itinerario": "Your Itinerary",
  "Transporte VIP": "VIP transportation",
  "Inversión Total": "Total Investment",
  "Yates de Lujo": "Luxury Yachts",
  "Selecciona los servicios exclusivos para crear un paquete a tu medida.": "Select exclusive services to create a package tailored to you.",
  "Localizador:": "Locator:",
  "Check-in:": "Check-in:",
  "Total Pagado:": "Total Paid:",
  "Pago Seguro & Confirmación Instantánea": "Secure Payment & Instant Confirmation",
  "¡Cuenta creada exitosamente! Ya puedes iniciar sesión con tu correo.": "Account created successfully! You can now log in with your email.",
  "Crea una contraseña ahora para guardar tus datos y acceder a un panel privado con tu historial.": "Create a password now to save your data and access a private dashboard with your history.",
  "tu@correo.com": "you@mail.com",
  "Tu habitación en": "Your room in",
  "¡Reserva Confirmada!": "Confirmed Reservation!",
  "¡Gestiona tu Reserva!": "Manage your Reservation!",
  "Siguiente paso": "Next step",
  "Atrás": "Back",
  "Código de Descuento": "Discount Code",
  "Tarjeta": "Card",
  "Volver al Hotel": "Return to the Hotel",
  "Reservar Habitación": "Reserve Room",
  "Ir a Pago": "Go to Payment",
  "Este hotel no tiene métodos de pago configurados. Contacta soporte.": "This hotel does not have payment methods set up. Contact support.",
  "Simular Pago (Dev)": "Simulate Payment (Dev)",
  "Teléfono (WhatsApp)": "Telephone (WhatsApp)",
  "Horarios": "Schedules",
  "Ingresa tu código": "Enter your code",
  "Información Útil": "Useful Information",
  "Volver al catálogo": "Return to catalog",
  "Para enviar la confirmación": "To send confirmation",
  "Sobre el Hotel": "About the Hotel",
  "Verificando pago...": "Verifying payment...",
  "Crea tu contraseña": "Create your password",
  "Hotel no encontrado": "Hotel not found",
  "Ej. Juan Pérez": "Ex. Juan Pérez",
  "Seleccionar": "Select",
  "Contacto": "Contact",
  "Políticas": "Policies",
  "Cancelación Gratuita": "Free Cancellation",
  "Tu Estancia": "Your Stay",
  "Perfil No Disponible": "Profile Not Available",
  "por noche": "per night",
  "VamosJuntos": "Let's go together",
  "Selecciona una habitación de la lista para verificar fechas y disponibilidad.": "Select a room from the list to check dates and availability.",
  "No hay habitaciones disponibles por el momento.": "There are no rooms available at the moment.",
  "Multimedia": "Multimedia",
  "Volver al Inicio": "Return to Home",
  "Perfil Profesional": "Professional Profile",
  "Idiomas:": "Languages:",
  "Este perfil de operador aún no está publicado o se encuentra temporalmente inactivo.": "This operator profile is not yet published or is temporarily inactive.",
  "Especialidades del Operador": "Operator Specialties",
  "Certificaciones Oficiales": "Official Certifications",
  "Explorar Catálogo": "Explore Catalog",
  "),\r\n    bio: (": "),\r\n    bio: (",
  "Galería de Experiencias": "Experience Gallery",
  "Valoraciones": "Ratings",
  "Facebook": "Facebook",
  "Duración": "Duration",
  "Reserva tu Próximo Tour": "Book your Next Tour",
  "email@example.com": "email@example.com",
  ") : null,\r\n    social: (": ") : null,\r\n    social: (",
  "Ver Más Experiencias": "See More Experiences",
  "Contactar Operador": "Contact Operator",
  "Testimonios de Huéspedes": "Guest Testimonials",
  "Conéctate a través de canales directos para solicitar itinerarios especiales o coordinar traslados ejecutivos en toda la Riviera Maya.": "Connect through direct channels to request special itineraries or coordinate executive transfers throughout the Riviera Maya.",
  "Origen:": "Origin:",
  "Destino:": "Destination:",
  "Contactar por WhatsApp": "Contact by WhatsApp",
  "Socios Estratégicos": "Strategic Partners",
  "John Doe": "John Doe",
  "john@example.com": "john@example.com",
  ") : null,\r\n    cta: (": ") : null,\r\n    cta: (",
  "),\r\n    mission: (": "),\r\n    mission: (",
  "Ready To Create Your Next": "Ready To Create Your Next",
  "¿Listo Para Crear Tu Próximo": "Ready to Create Your Next",
  "Contraseña Actual": "Current Password",
  "Mexico": "Mexico",
  "Mínimo 8 caracteres": "Minimum 8 characters",
  "Nueva Contraseña": "New Password",
  "Gestión de Contraseña": "Password Management",
  "Street address, Apt/Suite": "Street address, Apt/Suite",
  "Confirmar Nueva Contraseña": "Confirm New Password",
  "Actualiza tu contraseña de acceso": "Update your access password",
  "¡Contraseña actualizada exitosamente!": "Password updated successfully!",
  "Ingresa tu contraseña actual": "Enter your current password",
  "Repite la nueva contraseña": "Repeat the new password",
  "Total": "Total",
  "Ana Martínez": "Ana Martinez",
  "Selecciona tu": "Select your",
  "Embarcación": "boat",
  "Payment Successful!": "Payment Successful!",
  "Select Your": "Select Your",
  "Return to Home": "Return to Home",
  "Vessel": "Vessel",
  "Conectado como": "Connected as",
  "Laura Rojas": "Laura Rojas",
  "Javier Pérez": "Javier Perez",
  "Cerrar Notificación": "Close Notification",
  "Notificación Disciplinaria Oficial": "Official Disciplinary Notification",
  "Panel de Control": "Dashboard",
  "Panel de Reservas": "Bookings",
  "Cambiar Contraseña": "Change Password",
  "Cerrar Sesión": "Log Out",
  "Administrador": "Administrator",
  "Guardar Cambios": "Save Changes",
  "Guardando...": "Saving...",
  "Todos los campos son obligatorios": "All fields are required",
  "La nueva contraseña y la confirmación no coinciden": "The new password and confirmation do not match",
  "La nueva contraseña debe tener al menos 8 caracteres": "The new password must be at least 8 characters long",
  "Error al actualizar la contraseña": "Error updating password",
  "Error desconocido": "Unknown error"
,
  "App Icon": "app icon",
  "Promise": "Promise",
  "SW Registration Failed": "SW Registration Failed",
  "Experiences": "experiences",
  "Unique": "Unique",
  "SW Registered": "SW Registered",
  "Atracciones turísticas": "Tourist attractions",
  "SW Unregistered in development mode": "SW Unregistered in development mode",
  "User accepted the install prompt": "User accepted the install prompt",
  "Tourist attractions": "Tourist attractions",
  "Destination": "Destination",
  "Juan Carlos Pérez": "Juan Carlos Perez",
  "Destino": "Destination",
  "Paradise beaches": "Paradise beaches",
  "Únicas": "Unique",
  "Playas paradisiacas": "Paradise beaches",
  "Driver VIP": "VIP Driver",
  "Paradises": "Paradises",
  "Coastal": "Coastal",
  "From hidden bays to vibrant and exclusive beaches.": "From hidden bays to vibrant and exclusive beaches.",
  "Reserva con tu Concierge VIP": "Book with your VIP Concierge",
  "Roberto Gómez": "Roberto Gomez",
  "Driver": "driver",
  "Executive Driver": "Executive Driver",
  "Miguel Ángel Torres": "Miguel Angel Torres",
  "VW Transporter": "VW Transporter",
  "Error loading catalog:": "Catalog loading error:",
  "Chevrolet Suburban": "Chevrolet Suburban",
  "Professional Driver": "Professional Driver",
  "Toyota Sienna XL": "Toyota Sienna XL",
  "🚖 Seleccionar Chofer": "🚖 Select Driver",
  "Error desconocido": "Unknown error",
  "Unknown error": "Unknown error",
  "Ingresa tu correo electrónico": "Enter your email",
  "fee": "fee",
  "Destinos": "Destinations",
  "Error al enviar código": "Error sending code",
  "Error sending code": "Error sending code",
  "Enter your email address": "Enter your email address",
  "Content-Type": "Content-Type",
  "Backspace": "Backspace",
  "Passwords do not match": "Passwords do not match",
  "Complete password fields": "Complete password fields",
  "Error resending": "Resending error",
  "Error al reenviar": "Failed to resend",
  "Ingresa los 6 dígitos completos del código": "Enter the full 6 digits of the code",
  "Code expired. Request a new one.": "Code expired. Request a new one.",
  "Completa los campos de contraseña": "Complete the password fields",
  "El código expiró. Solicita uno nuevo.": "The code has expired. Request a new one.",
  "Please enter the complete 6-digit code": "Please enter the complete 6-digit code",
  "Las contraseñas no coinciden": "Passwords do not match",
  "¡Contraseña Actualizada!": "Password Updated!",
  "The new password must be at least 8 characters": "The new password must be at least 8 characters",
  "Incorrect code or error verifying": "Incorrect code or error verifying",
  "Código incorrecto o error al verificar": "Wrong code or error while verifying",
  "Password Updated!": "Password Updated!",
  "Go to Login": "Go to Login",
  "Verify Your Identity": "Verify Your Identity",
  "Ir a Iniciar Sesión": "Go to Login",
  "Verifica tu Identidad": "Verify your Identity",
  "Reset Password": "Reset Password",
  "Restablecer Contraseña": "Reset Password",
  "Enter 6-Digit Code": "Enter 6-Digit Code",
  "Resending...": "Resending...",
  "Code expires in": "Code expires in",
  "Repeat new password": "Repeat new password",
  "We sent a code to": "We sent a code to",
  "Enviamos un código a": "We send a code to",
  "El código expira en": "The code expires in",
  "Ingresa el Código de 6 dígitos": "Enter the 6-digit Code",
  "Reenviando...": "Forwarding...",
  "Reenviar Código": "Resend Code",
  "Email Address": "Email Address",
  "Send Code": "Send Code",
  "Recuperar Contraseña": "Recover Password",
  "Volver al Login": "Return to Login",
  "Back to Login": "Back to Login",
  "Recover Password": "Recover Password",
  "Resend Code": "Resend Code",
  "Didn": "Didn",
  "Enviar Código": "Send Code",
  "Unauthorized": "Unauthorized",
  "Disponible": "Available",
  "Activa": "Active",
  "Failed to create reservation": "Failed to create reservation",
  "Error creating hotel reservation:": "Error creating hotel reservation:",
  "Error fetching public hotels:": "Fetching public hotels error:",
  "Error cargando hoteles": "Error loading hotels",
  "Room not found": "Room not found",
  "Error cargando hotel": "Error loading hotel",
  "Error en el pago": "Payment error",
  "La contraseña debe tener al menos 6 caracteres": "Password must be at least 6 characters",
  "Procesando...": "Processing...",
  "Código inválido": "Invalid code",
  "Reserva Hotel: ${hotel.name} - ${room.type}": "Hotel Reservation: ${hotel.name} - ${room.type}",
  "Error fetching hotel reservations:": "Error fetching hotel reservations:",
  "Error al guardar la reserva:": "Error saving reservation:",
  "Pagar ${amount.toLocaleString()} USD": "Pay ${amount.toLocaleString()} USD",
  "Failed to fetch hotel reservations": "Failed to fetch hotel reservations",
  "Error al crear la cuenta": "Error creating account",
  "PayPal": "PayPal",
  "Aplicar": "Apply",
  "Check-out": "Check out",
  "Check-in": "Check-in",
  "Huéspedes": "Guests",
  "Adulto": "Adult",
  "Error de conexión": "Connection error",
  "Adultos": "Adults",
  "Crear Cuenta": "Create Account",
  "Hotel ${hotel.name} - ${room.type}": "Hotel ${hotel.name} - ${room.type}",
  "Resort": "Resort",
  "Hostal": "Hostel",
  "Credenciales inválidas. Intenta de nuevo.": "Invalid credentials. Try again.",
  "Luxury Hotels": "Luxury Hotels",
  "No disponible": "Not available",
  "Premium travel packages, yachts, and VIP transport.": "Premium travel packages, yachts, and VIP transport.",
  "VamosJuntos Luxury Travel": "Let's GoTogether Luxury Travel",
  "Invalid credentials. Please try again.": "Invalid credentials. Please try again.",
  "Login error:": "Login error:",
  "Habitaciones Disponibles": "Available Rooms",
  "Panel de Administración": "Administration Panel",
  "Usuario": "User",
  "Contraseña": "Password",
  "Algo salió mal. Por favor intenta más tarde.": "Something went wrong. Please try again later.",
  "Username": "Username",
  "Entrar al Panel": "Enter the Panel",
  "Something went wrong. Please try again later.": "Something went wrong. Please try again later.",
  "Enter Panel": "Enter Panel",
  "Back to site": "Back to site",
  "Administration Panel": "Administration Panel",
  "Forgot your password?": "Forgot your password?",
  "Regístrate aquí": "Register here",
  "¿Olvidaste tu contraseña?": "Forgot your password?",
  "Recupérala aquí": "Get it here",
  "Don": "Gift",
  "¿No tienes cuenta?": "Don't have an account?",
  "Recover it here": "Recover it here",
  "Error loading operator tours:": "Error loading operator tours:",
  "Register here": "Register here",
  "Operador VIP | VamosJuntos": "VIP Operator | Let's go together",
  "Date": "date",
  "Instagram": "instagram",
  ") : null,\r\n    social: (": ") : null,\r\n    social: (",
  "Fecha": "Date",
  "WhatsApp": "WhatsApp",
  "),\r\n    bio: (": "),\r\n    bio: (",
  ") : null,\r\n    tours: operatorTours.length > 0 ? (": ") : null,\r\n    tours: operatorTours.length > 0 ? (",
  "Operador Turístico Autorizado": "Authorized Tour Operator",
  "Resumen de Reserva": "Reservation Summary",
  "Booking Summary": "Booking Summary",
  "Discount": "discount",
  "Vehículo": "Vehicle",
  "Pasajeros": "Passengers",
  "Vehicle": "vehicle",
  "Monto Base": "Base Amount",
  "Cargo Operativo (5%)": "Operational Charge (5%)",
  "Operating Fee (5%)": "Operating Fee (5%)",
  "Passengers": "Passengers",
  "Start Time": "Start Time",
  "Base Amount": "Base Amount",
  "Descuento": "Discount",
  "Total a Pagar": "Total to Pay",
  "Datos": "Data",
  "Confirmar": "Confirm",
  "Confirm": "Confirm",
  "Data": "Data",
  "Volver": "Return",
  "Plan Your Experience": "Plan Your Experience",
  "Total to Pay": "Total to Pay",
  "Invalid code": "Invalid code",
  "Número de Pasajeros": "Number of Passengers",
  "Next Step": "Next Step",
  "Select Date": "Select Date",
  "Selecciona la Fecha": "Select the Date",
  "Planifica tu Experiencia": "Plan your Experience",
  "Number of Passengers": "Number of Passengers",
  "Scheduled start time:": "Scheduled start time:",
  "Capacidad máxima del transporte:": "Maximum transport capacity:",
  "Maximum transport capacity:": "Maximum transport capacity:",
  "Hora de inicio programada:": "Scheduled start time:",
  "Last Name": "Last Name",
  "Nombre": "Name",
  "Siguiente Paso": "Next Step",
  "Phone": "Telephone",
  "Apellido": "Last name",
  "First Name": "First Name",
  "Tus Datos": "Your Data",
  "Ej. Pérez": "Ex. Pérez",
  "Your Details": "Your Details",
  "Ej. Juan": "Ex. Juan",
  "Country": "Country",
  "Confirmation": "confirmation",
  "Confirmación": "Confirmation",
  "Confirm Details": "Confirm Details",
  "Special requests...": "Special requests...",
  "Confirmar Datos": "Confirm Data",
  "Ej. México": "Ex. Mexico",
  "Notes (Optional)": "Notes (Optional)",
  "Notas (Opcional)": "Notes (Optional)",
  "Peticiones especiales...": "Special requests...",
  "Itinerario Detallado": "Detailed Itinerary",
  "Hora de Salida": "Departure time",
  "Parada ${idx + 1}": "Stop ${idx + 1}",
  "Detailed Itinerary": "Detailed Itinerary",
  "Pickup Point": "Pickup Point",
  "Punto de Recogida": "Collection Point",
  "Final Destination": "Final Destination",
  "Destino Final": "Final Destination",
  "Stop ${idx + 1}": "Stop ${idx + 1}",
  "Departure Time": "Departure Time",
  "Apply": "Apply",
  "Titular de la Reserva": "Reservation Holder",
  "Enter code": "Enter code",
  "Confirmar Ahora": "Confirm Now",
  "Booking Holder": "Booking Holder",
  "Confirm Now": "Confirm Now",
  "Protected Reservation": "Protected Reservation",
  "Reserva Protegida": "Protected Reserve",
  "We will lock availability immediately.": "We will lock availability immediately.",
  "Bloquearemos la disponibilidad de inmediato.": "We will block availability immediately.",
  "Pay Securely": "Pay Securely",
  "Payment failed": "Payment failed",
  "Procesando Pago...": "Processing Payment...",
  "Pagar de forma Segura": "Pay safely",
  "Processing Payment...": "Processing Payment...",
  "El pago ha fallado": "Payment has failed",
  "Password must be at least 6 characters": "Password must be at least 6 characters",
  "Failed to save reservation": "Failed to save reservation",
  "There was an error saving your reservation.": "There was an error saving your reservation.",
  "Hubo un error al registrar la reserva.": "There was an error when registering the reservation.",
  "Pago Requerido": "Payment Required",
  "Error creating account": "Error creating account",
  "Pagos procesados de forma segura con cifrado SSL.": "Payments processed securely with SSL encryption.",
  "Connection error": "connection error",
  "Payment Required": "Payment Required",
  "Obteniendo métodos de pago...": "Obtaining payment methods...",
  "Secure payments processed with SSL encryption.": "Secure payments processed with SSL encryption.",
  "Loading payment gateway...": "Loading payment gateway...",
  "Fetching payment options...": "Fetching payment options...",
  "Cargando pasarela de pago...": "Loading payment gateway...",
  "Confirmed": "Confirmed",
  "Estatus": "Status",
  "Por favor, no cierres esta ventana.": "Please do not close this window.",
  "¡Reserva Exitosa!": "Successful Reservation!",
  "Booking Code / Locator": "Booking Code / Locator",
  "Successful Booking!": "Successful Booking!",
  "Confirming reservation...": "Confirming reservation...",
  "Código de Reserva / Localizador": "Reservation Code / Locator",
  "Please do not close this window.": "Please do not close this window.",
  "Confirmando reserva...": "Confirming reservation...",
  "Mínimo 6 caracteres": "Minimum 6 characters",
  "Itinerario": "Itinerary",
  "Back to Homepage": "Back to Homepage",
  "Crea tu Cuenta": "Create your Account",
  "Itinerary": "Itinerary",
  "Print Voucher / Receipt": "Print Voucher / Receipt",
  "Minimum 6 characters": "Minimum 6 characters",
  "Save Password & Create Account": "Save Password & Create Account",
  "Create your Account": "Create your Account",
  "Imprimir Voucher / Recibo": "Print Voucher / Receipt",
  "¡Cuenta creada con éxito! Ya puedes iniciar sesión.": "Account created successfully! You can now log in.",
  "Detalles del Paquete": "Package Details",
  "Capacity": "Capacity",
  "Operated by:": "Operated by:",
  "VamosJuntos VIP": "Let's goTogether VIP",
  "Guardar y Crear Cuenta": "Save and Create Account",
  "Account created successfully! You can now log in.": "Account created successfully! You can now log in.",
  "Experiencia 5 Estrellas": "5 Star Experience",
  "Operado por:": "Operated by:",
  "Package Details": "Package Details",
  "Asientos": "Seating",
  "Reserve": "Reserve",
  "Personas": "People",
  "Capacidad": "Ability",
  "People": "People",
  "Transporte Premium Incluido": "Premium Transportation Included",
  "Premium Transport Included": "Premium Transport Included",
  "Itinerario Sugerido": "Suggested Itinerary",
  "Suggested Itinerary": "Suggested Itinerary",
  "Seats": "Seats",
  "Reserva": "Booking",
  "Contacto de soporte": "Support Contact",
  "Sin nombre": "Unnamed",
  "Agente Autorizado": "Authorized Agent",
  "Departure point": "Departure point",
  "Authorized Agent": "Authorized Agent",
  "Support Contact": "Support Contact",
  "Unnamed Package": "Unnamed Package",
  "Experiencia exclusiva diseñada para ti.": "Exclusive experience designed for you.",
  "Exclusive experience designed for you.": "Exclusive experience designed for you.",
  "Premium": "Premium",
  "Punto de partida": "Starting point",
  "All": "all",
  "Item": "Item",
  "Punto de destino": "destination point",
  "Destination point": "Destination point",
  "Yachts": "Yachts",
  "Gourmet": "Gourmet",
  "Luxury SUV": "Luxury SUV",
  "Beaches": "Beaches",
  "Mostrando": "Showing",
  "¿A dónde quieres ir?": "Where do you want to go?",
  "Hotels": "Hotels",
  "Syncing luxury catalog...": "Syncing luxury catalog...",
  "Sincronizando catálogo de lujo...": "Synchronizing luxury catalog...",
  "Explora el Caribe de Lujo": "Explore the Luxury Caribbean",
  "Luxury Mexico Ruins": "Luxury Mexico Ruins",
  "Showing": "Showing",
  "Explore Luxury Caribbean": "Explore Luxury Caribbean",
  "Where would you like to go?": "Where would you like to go?",
  "Exclusive": "exclusive",
  "Book Now": "Book Now",
  "¿Buscas algo totalmente único?": "Looking for something totally unique?",
  "No encontramos coincidencias": "We found no matches",
  "Looking for something completely unique?": "Looking for something completely unique?",
  "Build Custom Tour": "Build Custom Tour",
  "View all catalog": "View all catalog",
  "Contact via WhatsApp": "Contact via WhatsApp",
  "No matches found": "No matches found",
  "Ver todo el catálogo": "See the entire catalog",
  "Back to Home": "Back to Home",
  "Quiénes Somos | VamosJuntos": "Who We Are | Let's go together",
  "VamosJuntos Hero": "Let's GoTogether Hero",
  "Armar Tour Personalizado": "Create a Personalized Tour",
  "Luxury Yacht": "Luxury Yacht",
  "Tour Operators": "Tour Operators",
  "About Us | VamosJuntos": "About Us | Let's go together",
  "Section Unavailable": "Section Unavailable",
  "VamosJuntos Experience": "VamosJuntos Experience",
  "Sección No Disponible": "Section Not Available",
  "Our Mission": "Our Mission",
  "Nuestra Visión": "Our Vision",
  "Nuestros Valores Corporativos": "Our Corporate Values",
  "Trayectoria y Crecimiento": "Trajectory and Growth",
  "Talent & Leadership": "Talent & Leadership",
  "Our Timeline": "Our Timeline",
  "Our Vision": "Our Vision",
  "Nuestra Línea de Tiempo": "Our Timeline",
  "Trajectory & Growth": "Trajectory & Growth",
  "Our Corporate Values": "Our Corporate Values",
  "Conectar": "Connect",
  "Connect": "Connect",
  "Nuestro Equipo Directivo": "Our Management Team",
  "Gallery of Moments": "Gallery of Moments",
  "Talento y Liderazgo": "Talent and Leadership",
  "Experiencias de Ensueño": "Dream Experiences",
  "VamosJuntos Gallery": "VamosJuntos Gallery",
  "Galería de Momentos": "Moments Gallery",
  "Our Executive Team": "Our Executive Team",
  "Dream Experiences": "Dream Experiences",
  "General": "General",
  "),\r\n    mission: (": "),\r\n    mission: (",
  "Diseñar Mi Viaje": "Design My Trip",
  "Explorar Destinos": "Explore Destinations",
  "Opiniones Reales": "Real Opinions",
  "Design My Trip": "Design My Trip",
  "Explore Destinations": "Explore Destinations",
  "What Our Clients Say": "What Our Clients Say",
  "Lo Que Dicen Nuestros Clientes": "What Our Clients Say",
  "Real Reviews": "Real Reviews",
  ") : null,\r\n    cta: (": ") : null,\r\n    cta: (",
  "¡Registro Completo!": "Complete Registration!",
  "Código incorrecto": "Wrong code",
  "Your account as": "Your account as",
  "Registration Complete!": "Registration Complete!",
  "Recuerdo Inolvidable?": "Unforgettable memory?",
  "Unforgettable Memory?": "Unforgettable Memory?",
  "Ingresa los 6 dígitos": "Enter the 6 digits",
  "Incorrect code": "Incorrect code",
  "Enter the 6 digits": "Enter the 6 digits",
  "Tu contraseña temporal de acceso es:": "Your temporary access password is:",
  "Transporter": "Transporter",
  "Tu cuenta de": "Your account",
  "Operator": "Operator",
  "Por favor guárdala en un lugar seguro.": "Please keep it in a safe place.",
  "We sent a 6-digit code to": "We sent a 6-digit code to",
  "Please save it in a safe place.": "Please save it in a safe place.",
  "Your temporary access password is:": "Your temporary access password is:",
  "Verifica tu correo": "Check your email",
  "Verify your email": "Verify your email",
  "Enviamos un código de 6 dígitos a": "We send a 6-digit code to",
  "El código ha expirado.": "The code has expired.",
  "Available if code expires": "Available if code expires",
  "Disponible si el código expira": "Available if code expires",
  "Reenviar código": "Resend code",
  "Verificar Código": "Verify Code",
  "Back to form": "Back to form",
  "Resend code": "Resend code",
  "Verify Code": "Verify Code",
  "The code has expired.": "The code has expired.",
  "No autorizado": "Unauthorized",
  "Guardar Cambios": "Save Changes",
  "Transporte y traslados": "Transportation and transfers",
  "Volver al formulario": "Return to form",
  "La nueva contraseña y la confirmación no coinciden": "New password and confirmation do not match",
  "Error al actualizar la contraseña": "Error updating password",
  "Gestión y operación de servicios": "Management and operation of services",
  "Management and operation of services": "Management and operation of services",
  "Transportation and transfers": "Transportation and transfers",
  "Todos los campos son obligatorios": "All fields are required",
  "Status:": "Status:",
  "Pending": "Pending",
  "Error al consultar las reservas": "Error when consulting reservations",
  "Error al consultar la reserva": "Error when consulting the reservation",
  "Fetch reservations error:": "Fetch reservations error:",
  "No se encontró ninguna reserva con esos datos.": "No reservation was found with this data.",
  "Auth check failed:": "Auth check failed:",
  "Taxi Asignado": "Assigned Taxi",
  "Tracking Error:": "Tracking Error:",
  "Assigned Cab": "Assigned Cab",
  "Error de conexión. Inténtalo de nuevo.": "Connection error. Try again.",
  "Booking Tracking": "Booking Tracking",
  "Connection failure. Please retry.": "Connection failure. Please retry.",
  "Seguimiento de Reservas": "Reservations Tracking",
  "Detalle de Reserva": "Reservation Detail",
  "Consulta la información y estatus de tu reserva.": "Check the information and status of your reservation.",
  "Booking Details": "Booking Details",
  "My Reservations Panel": "My Reservations Panel",
  "Mi Panel de Reservas": "My Reservations Panel",
  "History of your purchases and custom quotes.": "History of your purchases and custom quotes.",
  "Locator Code (e.g., VJ-XXXXXX)": "Locator Code (e.g., VJ-XXXXXX)",
  "Tus Paquetes Personalizados": "Your Personalized Packages",
  "Localizador (Ej. VJ-XXXXXX)": "Locator (Ex. VJ-XXXXXX)",
  "Find Reservation": "Find Reservation",
  "Buscar Reserva": "Search Reservation",
  "Find your Reservation": "Find your Reservation",
  "Loading panel...": "Loading panel...",
  "Cargando panel...": "Loading panel...",
  "Your Custom Packages": "Your Custom Packages",
  "Consulta tu Reserva": "Check your Reservation",
  "Guests": "Guests",
  "Ver Catálogo": "See Catalog",
  "No tienes reservas activas": "You have no active reservations",
  "Descargar Comprobante PDF": "Download PDF Receipt",
  "Explora nuestros paquetes y hoteles.": "Explore our packages and hotels.",
  "Explore our luxury packages and hotels.": "Explore our luxury packages and hotels.",
  "Locator Code:": "Locator Code:",
  "Download PDF Voucher": "Download PDF Voucher",
  "View Catalog": "View Catalog",
  "No active reservations": "Do not activate reservations",
  "Close": "Close",
  "Cerrar": "Close",
  "Driver VIP •": "VIP Driver •",
  ": (isPending ?": ": (isPending ?",
  "Colección de": "Collection of",
  "Yates Premium": "Premium Yachts",
  "Desde ${price} USD": "From ${price} USD",
  "Yacht Collection": "Yacht Collection",
  "Yachts at the beach": "Yachts on the beach",
  "Yates en la playa": "yachts on the beach",
  "Desde": "From",
  "Activo": "Asset",
  "From": "From",
  "Ver detalles": "See details",
  "Abierta": "open",
  "View details": "View details",
  "View all": "View all",
  "Ver todos": "See all",
  "Capacidad cómoda: ${item.capacity} personas": "Comfortable capacity: ${item.capacity} people",
  "Comfortable capacity: ${item.capacity} people": "Comfortable capacity: ${item.capacity} people",
  "Image": "Image",
  "Información": "Information",
  "No description available.": "No description available.",
  "Information": "Information",
  "Sin descripción disponible.": "No description available.",
  "Capacidad: ${item.capacity}": "Capacity: ${item.capacity}",
  "Capacity: ${item.capacity}": "Capacity: ${item.capacity}",
  "Contact for Booking": "Contact for Booking",
  "Precio desde": "Price from",
  "Price from": "Price from",
  "Gimnasio": "Gym",
  "Amenidades": "Amenities",
  "Alberca": "Swimming pool",
  "Amenities": "Amenities",
  "WiFi": "Wi-Fi",
  "Restaurante": "Restaurant",
  "Restaurant": "Restaurant",
  "Pool": "Pool",
  "Gym": "Gym",
  "Contactar para Reservar": "Contact to Reserve",
  "Up to ${room.maxCapacity} guests": "Up to ${room.maxCapacity} guests",
  "Una experiencia única en": "A unique experience in",
  "Ver Habitaciones y Reservar": "See Rooms and Book",
  "Hasta ${room.maxCapacity} huéspedes": "Up to ${room.maxCapacity} guests",
  "Detalles del Hotel": "Hotel Details",
  "A unique experience in": "A unique experience in",
  "View Rooms & Book": "View Rooms & Book",
  "Tipos de Habitación": "Room Types",
  "Hotel Details": "Hotel Details",
  "Room Types": "Room Types",
  "Carlos Gómez": "Carlos Gomez",
  "Book": "book",
  "Entendido y Confirmar Lectura": "Understood and Confirm Reading",
  "Registrando Confirmación...": "Registering Confirmation...",
  "Error confirming warning:": "Error confirming warning:",
  "Error loading user warning alerts:": "Error loading user warning alerts:",
  "Switch to English": "Switch to English",
  "VamosJuntos Logo": "Let's Go Together Logo",
  "Cambiar a Español": "Switch to Spanish"
};

export default function PublicTranslator({ children }: { children: React.ReactNode }) {
    const { language } = useLanguage();
    const [mounted, setMounted] = useState(false);

    useEffect(() => {
        setMounted(true);
    }, []);

    useEffect(() => {
        if (!mounted || language !== 'en') return;

        let timeoutId: NodeJS.Timeout;

        const translateNode = (node: Node) => {
            if (node.nodeType === Node.TEXT_NODE) {
                const text = node.nodeValue?.trim();
                if (text && publicTranslationMap[text]) {
                    node.nodeValue = node.nodeValue!.replace(text, publicTranslationMap[text]);
                }
            } else if (node.nodeType === Node.ELEMENT_NODE) {
                const el = node as Element;
                if (el.tagName === 'SCRIPT' || el.tagName === 'STYLE') return;
                
                // Translate placeholder
                if (el.hasAttribute('placeholder')) {
                    const placeholder = el.getAttribute('placeholder')?.trim();
                    if (placeholder && publicTranslationMap[placeholder]) {
                        el.setAttribute('placeholder', publicTranslationMap[placeholder]);
                    }
                }

                // Translate title
                if (el.hasAttribute('title')) {
                    const title = el.getAttribute('title')?.trim();
                    if (title && publicTranslationMap[title]) {
                        el.setAttribute('title', publicTranslationMap[title]);
                    }
                }
                
                node.childNodes.forEach(translateNode);
            }
        };

        const runTranslation = () => {
            translateNode(document.body);
        };

        const observer = new MutationObserver((mutations) => {
            let shouldTranslate = false;
            for (const mutation of mutations) {
                if (mutation.addedNodes.length > 0 || mutation.type === 'characterData') {
                    shouldTranslate = true;
                    break;
                }
            }
            if (shouldTranslate) {
                clearTimeout(timeoutId);
                timeoutId = setTimeout(runTranslation, 50);
            }
        });

        runTranslation();
        observer.observe(document.body, { childList: true, subtree: true, characterData: true });

        return () => {
            observer.disconnect();
            clearTimeout(timeoutId);
        };
    }, [language, mounted]);

    return <>{children}</>;
}
