let currentLanguage = 'es';

const adminDictionary: Record<string, string> = {
  "Centro de Reportes": "Reports Center",
  "Análisis completo con gráficas interactivas": "Comprehensive analysis with interactive charts",
  "10 módulos disponibles": "10 modules available",
  "Reporte de Reservas": "Reservations Report",
  "Gestión de reservas, conversiones por estados, destinos populares y ocupación de cupos": "Management of reservations, conversions by state, popular destinations and coupon occupancy",
  "Reporte General (1.1)": "General Report (1.1)",
  "Por Estado (1.2)": "By Status (1.2)",
  "Por Destino (1.3)": "By Destination (1.3)",
  "Ocupación (1.4)": "Occupancy (1.4)",
  "Total Reservas": "Total Reservations",
  "Reservas Activas": "Active Reservations",
  "Ticket Promedio": "Average Ticket",
  "Conversión": "Conversion",
  "Semana": "Week",
  "Mes": "Month",
  "Trimestre": "Quarter",
  "Año": "Year",
  "Actualizar": "Refresh",
  "Exportar CSV": "Export CSV",
  "Filtros Avanzados": "Advanced Filters",
  "Ocultar Filtros": "Hide Filters",
  "Buscar por cliente, código, paquete, hotel...": "Search by customer, code, package, hotel...",
  "Catálogo de Playas": "Beaches Catalog",
  "Catálogo de Hoteles": "Hotels Catalog",
  "Catálogo de Atracciones": "Attractions Catalog",
  "Catálogo de Restaurantes": "Restaurants Catalog",
  "Catálogo de Taxis": "VIP Taxi Fleet",
  "Catálogo de Yates": "Premium Yacht Fleet",
  "Catálogo de Aeropuertos": "Airports Catalog",
  "Catálogo de Paquetes": "Packages Catalog",
  "Catálogo de Paquetes Turísticos": "Tour Packages Catalog",
  "Catálogo de Cupones": "Coupons Catalog",
  "Catálogo de Descuentos": "Discounts Catalog",
  "Gestión de destinos costeros y zonas de embarque.": "Management of coastal destinations and boarding zones.",
  "Gestión de aeropuertos y pistas de aterrizaje.": "Management of airports and landing tracks.",
  "Gestión de hoteles, resorts y villas de lujo.": "Management of luxury hotels, resorts, and boutique stays.",
  "Gestión de atracciones locales y actividades VIP.": "Management of local attractions and VIP activities.",
  "Gestión de restaurantes exclusivos y experiencias gastronómicas.": "Management of exclusive restaurants and gastronomic experiences.",
  "Gestión de vehículos VIP y transportistas autorizados.": "Management of VIP vehicles and authorized transporters.",
  "Gestión de la flota de yates y embarcaciones premium.": "Management of premium yachts and exclusive vessels.",
  "Gestión de cupones y códigos de descuento.": "Management of coupons and discount codes.",
  "Gestión de usuarios del sistema y permisos de acceso.": "Management of system users and access permissions.",
  "Panel de Administración": "Administration Panel",
  "Reportes Administrativos": "Administrative Reports",
  "Super Reportes Administrativos": "Super Administrative Reports",
  "Control de Reservas de Clientes": "Customer Reservations Control",
  "Control de Reservas de Hotel": "Hotel Reservations Control",
  "Solicitudes de Cotización": "Custom Quote Requests",
  "Gestión de Usuarios y Roles": "Users and Roles Management",
  "Facturación y Pagos": "Billing and Payments",
  "Reservas Totales": "Total Reservations",
  "Ingresos Generados": "Revenue Generated",
  "Reservas Hoy": "Reservations Today",
  "Nuevos Clientes": "New Customers",
  "Tasa Conversión": "Conversion Rate",
  "Servicios Disp.": "Available Services",
  "Serv. Ocupados": "Occupied Services",
  "Cancelaciones": "Cancellations",
  "Destino Top": "Top Destination",
  "Conductor Top": "Top Driver",
  "Yate Top": "Top Yacht",
  "Rte. Top": "Top Restaurant",
  "Bienvenido": "Welcome",
  "Administrador": "Administrator",
  "a su panel de control y estadísticas.": "to your control panel and statistics.",
  "Cargando métricas…": "Loading metrics...",
  "Añadir Playa": "Add Beach",
  "Añadir Aeropuerto": "Add Airport",
  "Añadir Hotel": "Add Hotel",
  "Añadir Atracción": "Add Attraction",
  "Añadir Restaurante": "Add Restaurant",
  "Añadir Yate": "Add Yacht",
  "Añadir Conductor": "Add Driver",
  "Añadir Vehículo": "Add Vehicle",
  "Añadir Usuario": "Add User",
  "Añadir Cupón": "Add Coupon",
  "Agregar Terminal": "Add Terminal",
  "Guardar": "Save",
  "Cancelar": "Cancel",
  "Cerrar": "Close",
  "Cerrar Mapa": "Close Map",
  "Ver Costa": "View Coast",
  "Ver Mapa": "View Map",
  "Ver Ubicación": "View Location",
  "Editar": "Edit",
  "Eliminar": "Delete",
  "Acciones": "Actions",
  "Crear": "Create",
  "Nuevo": "New",
  "Buscar": "Search",
  "Filtrar": "Filter",
  "Limpiar": "Clear",
  "Nombre / Tipo": "Name / Type",
  "Nombre": "Name",
  "Ubicación": "Location",
  "Estado": "Status",
  "Mapa": "Map",
  "Código IATA": "IATA Code",
  "Ciudad": "City",
  "Coordenadas": "Coordinates",
  "Estrellas": "Stars",
  "Habitaciones": "Rooms",
  "Tipo de Cocina": "Cuisine Type",
  "Dirección": "Address",
  "Modelo": "Model",
  "Placas": "License Plate",
  "Conductor Asignado": "Assigned Driver",
  "Chofer Asignado": "Assigned Driver",
  "Eslora": "Length",
  "Capacidad": "Capacity",
  "Precio por Hora": "Price per Hour",
  "Tripulación Incluida": "Crew Included",
  "Porcentaje": "Percentage",
  "Fecha Expiración": "Expiration Date",
  "Límite Usos": "Usage Limit",
  "Usos": "Uses",
  "Activo": "Active",
  "Inactivo": "Inactive",
  "Abierta": "Open",
  "Cerrada": "Closed",
  "Operativo": "Operational",
  "No Operativo": "Non-Operational",
  "IATA": "IATA",
  "IATA / Ciudad": "IATA / City",
  "Precio Base": "Base Price",
  "Habitaciones Disponibles": "Available Rooms",
  "Descripción": "Description",
  "Descripción del Hotel": "Hotel Description",
  "Sincronizando destinos...": "Synchronizing destinations...",
  "Sincronizando playas...": "Synchronizing beaches...",
  "Sincronizando aeropuertos...": "Synchronizing airports...",
  "Sincronizando hoteles...": "Synchronizing hotels...",
  "Sincronizando atracciones...": "Synchronizing attractions...",
  "Sincronizando restaurantes...": "Synchronizing restaurants...",
  "Sincronizando vehículos...": "Synchronizing vehicles...",
  "Sincronizando yates...": "Synchronizing yachts...",
  "Cargando...": "Loading...",
  "Cargando playas...": "Loading beaches...",
  "Cargando terminales...": "Loading terminals...",
  "Cargando hoteles...": "Loading hotels...",
  "Cargando atracciones...": "Loading attractions...",
  "Cargando restaurantes...": "Loading restaurants...",
  "Cargando vehículos...": "Loading vehicles...",
  "Cargando yates...": "Loading yachts...",
  "Cargando reservas...": "Loading reservations...",
  "Guardando...": "Saving...",
  "Procesando...": "Processing...",
  "No hay playas registradas": "No beaches registered",
  "No hay aeropuertos registrados": "No airports registered",
  "No hay hoteles registrados": "No hotels registered",
  "No hay atracciones registradas": "No attractions registered",
  "No hay restaurantes registrados": "No restaurants registered",
  "No hay vehículos registrados": "No vehicles registered",
  "No hay yates registrados": "No yachts registered",
  "No hay cupones registrados": "No coupons registered",
  "No hay usuarios registrados": "No users registered",
  "Las nuevas playas aparecerán aquí.": "New beaches will appear here.",
  "Los nuevos aeropuertos aparecerán aquí.": "New airports will appear here.",
  "Los nuevos hoteles aparecerán aquí.": "New hotels will appear here.",
  "Las nuevas atracciones aparecerán aquí.": "New attractions will appear here.",
  "Los nuevos restaurantes aparecerán aquí.": "New restaurants will appear here.",
  "Los nuevos vehículos aparecerán aquí.": "New vehicles will appear here.",
  "Los nuevos yates aparecerán aquí.": "New yachts will appear here.",
  "Los nuevos cupones aparecerán aquí.": "New coupons will appear here.",
  "Tipo de Playa": "Beach Type",
  "Tipo de Atracción": "Attraction Type",
  "Precio por Persona": "Price per Person",
  "Flota Taxis": "Taxi Fleet",
  "Flota de Yates": "Yacht Fleet",
  "Aeropuerto": "Airport",
  "Aeropuertos": "Airports",
  "Hoteles": "Hotels",
  "Playas": "Beaches",
  "Atracciones": "Attractions",
  "Restaurantes": "Restaurants",
  "Vehículos": "Vehicles",
  "Yates": "Yachts",
  "Cupones": "Coupons",
  "Usuarios": "Users",
  "Facturas": "Invoices",
  "Monto": "Amount",
  "Método Pago": "Payment Method",
  "Emisión": "Issued Date",
  "Localizador": "Locator",
  "Pasajeros": "Passengers",
  "Total Pagado": "Total Paid",
  "Fecha Viaje": "Travel Date",
  "Estatus": "Status",
  "Estatus Pago": "Payment Status",
  "Huéspedes": "Guests",
  "Noches": "Nights",
  "Entrada": "Check-in",
  "Salida": "Check-out",
  "Habitación": "Room",
  "Rol": "Role",
  "Permisos": "Permissions",
  "Usuario": "Username",
  "Contraseña": "Password",
  "Nombre Completo": "Full Name",
  "Teléfono": "Phone",
  "Correo": "Email",
  "Rango de Fechas": "Date Range",
  "Exportar": "Export",
  "Filtrar por": "Filter by",
  "Gráficas": "Charts",
  "Ventas": "Sales",
  "Reporte de Ventas": "Sales Report",
  "Logs de Actividad": "Activity Logs",
  "Auditoría": "Audit",
  "Historial": "History",
  "Generar": "Generate",
  "Detalle de Reserva": "Reservation Details",
  "Detalle de Solicitud": "Request Details",
  "Aprobar": "Approve",
  "Rechazar": "Reject",
  "Pendiente": "Pending",
  "Confirmada": "Confirmed",
  "Cancelada": "Cancelled",
  "Gestión de Reservas": "Reservations Management",
  "Listado completo de reservaciones y seguimiento de tours.": "Complete list of reservations and tour tracking.",
  "Todos los Estados": "All Statuses",
  "Es Hoy": "It's Today",
  "Próximas": "Upcoming",
  "Ya Pasaron": "Already Passed",
  "Cliente": "Customer",
  "Tour / Paquete": "Tour / Package",
  "Fecha de Reserva": "Reservation Date",
  "No se encontraron reservas con esos filtros.": "No reservations found with those filters.",
  "Cupón:": "Coupon:",
  "No hay reservas que coincidan.": "No matching reservations found.",
  "Buscar por cliente, email o paquete...": "Search by customer, email or package...",
  "Ya pasó": "Already passed",
  "Mañana": "Tomorrow",
  "Todas las Fechas": "All Dates",
  "Faltan ": "Left ",
  " días": " days",
  "Listado oficial de terminales aéreas en México.": "Official list of air terminals in Mexico.",
  "Buscar por...": "Search by...",
  "Financiero": "Financial",
  "Customers": "Customers",
  "Sales": "Sales",
  "Operational": "Operational",
  "Proveedores": "Suppliers",
  "Marketing": "Marketing",
  "Destinos": "Destinations",
  "BI Estratégico": "Strategic BI",
  "Administrativo": "Administrative",
  "Esta Semana": "This Week",
  "Reportes": "Reports",
  "Métricas de Conversión y Flujo de Estados": "Conversion Metrics and Status Flow",
  "Tiempo Promedio de Permanencia en Cada Estado": "Average Time in Each Status",
  "Reservas": "Reservations",
  "Evolución de Reservas e Ingresos": "Reservations and Revenue Evolution",
  "Distribución por Estado": "Distribution by Status",
  "Sincronizando...": "Synchronizing...",
  "Sincronizando datos...": "Synchronizing data...",
  "El código de cupón ya existe.": "The coupon code already exists.",
  "Error al crear cupón": "Error creating coupon",
  "Cupón creado con éxito": "Coupon created successfully",
  "Porcentaje Descuento": "Discount Percentage",
  "Ingresa el código": "Enter the code",
  "Código del Cupón": "Coupon Code",
  "Por favor llena todos los campos": "Please fill in all fields",
  "El descuento debe ser un porcentaje entre 1 y 100": "Discount must be a percentage between 1 and 100",
  "Error al crear código": "Error creating code",
  "¿Seguro que deseas eliminar este código?": "Are you sure you want to delete this code?",
  "Error al eliminar": "Error deleting",
  "Gestionar Cupones": "Manage Coupons",
  "Nuevo Código": "New Code",
  "Código Generado Automáticamente": "Automatically Generated Code",
  "Regenerar Código": "Regenerate Code",
  "Porcentaje de Descuento (%)": "Discount Percentage (%)",
  "Ej. 15": "E.g. 15",
  "Crear Código": "Create Code",
  "Códigos Creados": "Created Codes",
  "No hay códigos creados.": "No codes created.",
  "Usado": "Used",
  "Disponible": "Available"
,
  "Fecha/Hora:": "Date/Time:",
  "Usuario:": "User:",
  "Intento de acceso no autorizado": "Unauthorized access attempt",
  "Nivel 3: Solo Super Admin": "Level 3: Super Admin Only",
  "Verificando credenciales de seguridad...": "Verifying security credentials...",
  "Código de Seguridad:": "Security Code:",
  "Evento registrado:": "Recorded event:",
  "SEC-403-AUDIT": "SEC-403-AUDIT",
  "Acceso Restringido": "Restricted Access",
  "Esta sección contiene información confidencial de trazabilidad general, auditoría de logs técnicos y control financiero. Su perfil actual no cuenta con las credenciales necesarias.": "This section contains confidential information on general traceability, technical log auditing and financial control. Your current profile does not have the necessary credentials.",
  "Sincronizar": "Synchronize",
  "SUBTÍTULO": "CAPTION",
  "NUESTRA MISIÓN": "OUR MISSION",
  "Volver al Dashboard": "Return to Dashboard",
  "Información Corporativa Principal": "Main Corporate Information",
  "🔒 Quiénes Somos (Admin)": "🔒 Who We Are (Admin)",
  "Cargando contenidos institucionales...": "Loading institutional content...",
  "DESCRIPCIÓN LARGA (Rich Text Editor)": "LONG DESCRIPTION (Rich Text Editor)",
  "TÍTULO DE SECCIÓN": "SECTION TITLE",
  "Administración dinámica global de la sección institucional. Versión activa actual:": "Global dynamic administration of the institutional section. Current active version:",
  "IMAGEN DE FONDO (MOBILE)": "BACKGROUND IMAGE (MOBILE)",
  "TEXTO BOTÓN CTA": "CTA BUTTON TEXT",
  "ENLACE CTA (URL SLUG)": "CTA LINK (URL SLUG)",
  "NUESTRA VISIÓN": "OUR VISION",
  "VIDEO DE FONDO (.MP4 MAX 30MB)": "BACKGROUND VIDEO (.MP4 MAX 30MB)",
  "IMAGEN DE FONDO (DESKTOP)": "BACKGROUND IMAGE (DESKTOP)",
  "TÍTULO DE TEXTO EN EL BANNER": "TITLE TITLE ON BANNER",
  "Gestión Multimedia Hero Banner": "Multimedia Management Hero Banner",
  "OPACIDAD DE CAPA OVERLAY (%)": "OVERLAY LAYER OPACITY (%)",
  "Simulación Banner Hero (Previsualización)": "Banner Hero Simulation (Preview)",
  "AÑO": "YEAR",
  "TÍTULO": "QUALIFICATION",
  "Añadir": "Add",
  "Sin hitos registrados en la línea del tiempo.": "No milestones recorded on the timeline.",
  "DESCRIPCIÓN DEL ACONTECIMIENTO": "DESCRIPTION OF THE EVENT",
  "Añadir Nuevo Hito Histórico": "Add New Historical Landmark",
  "Crea y ordena la trayectoria histórica visual.": "Create and order the visual historical trajectory.",
  "Gestión del Equipo de Directivos": "Management of the Management Team",
  "Timeline / Hitos de la Empresa": "Timeline / Company Milestones",
  "FOTO REFERENCIAL (URL)": "REFERENCE PHOTO (URL)",
  "NOMBRE COMPLETO": "FULL NAME",
  "Destacado": "Outstanding",
  "BIOGRAFÍA CORTA": "SHORT BIOGRAPHY",
  "LINKEDIN URL": "LINKEDIN URL",
  "FOTO PERFIL (URL)": "PROFILE PHOTO (URL)",
  "Añadir Miembro": "Add Member",
  "CARGO CORPORATIVO": "CORPORATE POSITION",
  "Miembro Destacado (Principal)": "Featured Member (Main)",
  "Añadir Miembro del Equipo": "Add Team Member",
  "Galería Multimedia Corporativa": "Corporate Multimedia Gallery",
  "Activa": "Active",
  "Vincular": "Link",
  "Estado de Imagen:": "Image Status:",
  "CANTIDAD / NÚMERO": "QUANTITY/NUMBER",
  "Filtros y Categorías": "Filters and Categories",
  "SUFIJO / TEXTO": "SUFFIX / TEXT",
  "Añadir Métrica / Logro Corporativo": "Add Metric/Corporate Achievement",
  "Estadísticas Corporativas y Logros": "Corporate Statistics and Achievements",
  "Subir Imágenes y Documentos (Drag & Drop)": "Upload Images and Documents (Drag & Drop)",
  "Soporte para imágenes (PNG, WEBP, JPG), videos mp4 y catálogos PDF institucionales.": "Support for images (PNG, WEBP, JPG), mp4 videos and institutional PDF catalogs.",
  "Insertar": "Insert",
  "NOMBRE CLIENTE": "CUSTOMER NAME",
  "PAÍS": "COUNTRY",
  "ESTRELLAS": "STARS",
  "COMENTARIO": "COMMENT",
  "Optimización de Motores de Búsqueda (SEO)": "Search Engine Optimization (SEO)",
  "FOTO CLIENTE (URL)": "CUSTOMER PHOTO (URL)",
  "Testimonios de Clientes": "Customer Testimonials",
  "Crear Nuevo Testimonio": "Create New Testimonial",
  "ETIQUETA DESCRIPTIVA": "DESCRIPTIVE LABEL",
  "Historial y Versionado de Quiénes Somos": "History and Versioning of Who We Are",
  "Estructura y Orden de la Página": "Structure and Order of the Page",
  "SEO FRIENDLY SLUG (RUTA URL)": "SEO FRIENDLY SLUG (URL PATH)",
  "OPEN GRAPH SHARE IMAGE (FACEBOOK / TWITTER)": "OPEN GRAPH SHARE IMAGE (FACEBOOK / TWITTER)",
  "META DESCRIPTION (EXTRACTO BUSCADORES)": "META DESCRIPTION (SEARCH ENGINE EXTRACT)",
  "META TITLE (TÍTULO GOOGLE)": "META TITLE (GOOGLE TITLE)",
  "Define en qué orden aparecen las secciones en la vista pública.": "Defines in which order sections appear in public view.",
  "Sin revisiones de contenido anteriores registradas.": "No previous content reviews recorded.",
  "KEYWORDS (PALABRAS CLAVE)": "KEYWORDS (KEYWORDS)",
  "No hay secciones configuradas. Por favor, guarda para inicializar.": "There are no sections configured. Please save to initialize.",
  "Detalles sobre lo ocurrido...": "Details about what happened...",
  "https://linkedin.com/in/...": "https://linkedin.com/in/...",
  "Ej: Lanzamiento del portal": "Ex: Launch of the portal",
  "https://...": "https://...",
  "Ej: 2012": "Ex: 2012",
  "Ej: Director Ejecutivo": "Ex: Executive Director",
  "Restaurar Versión": "Restore Version",
  "Ej: https://...": "Ex: https://...",
  "Ej: Alejandro Ruiz": "Ex: Alejandro Ruiz",
  "PUBLICADA Y ACTIVA": "PUBLISHED AND ACTIVE",
  "Excelente experiencia, súper recomendados...": "Excellent experience, highly recommended...",
  "Pegar URL de imagen / archivo...": "Paste image/file URL...",
  "Breve reseña profesional...": "Brief professional review...",
  "Esta sección requiere un rol de operador o administrador autorizado.": "This section requires an authorized operator or administrator role.",
  "Ej: Clientes satisfechos": "Ex: Satisfied customers",
  "Ej: 500 o 15": "Ex: 500 or 15",
  "Ej: Italia": "Ex: Italy",
  "Ej: Sophia Loren": "Ex: Sophia Loren",
  "Ej: + o Años": "Ex: + or Years",
  "Categoría (Ej: Yates)": "Category (Ex: Yachts)",
  "Recargar": "Recharge",
  "AÑOS DE EXPERIENCIA": "YEARS OF EXPERIENCE",
  "👥 Perfil de Operador": "👥 Operator Profile",
  "UBICACIÓN PRINCIPAL": "MAIN LOCATION",
  "• Versión activa:": "• Active version:",
  "Información Profesional de Contacto": "Professional Contact Information",
  "Personaliza tu portafolio de operador. Nombre público:": "Customize your operator portfolio. Public name:",
  "NOMBRE DEL OPERADOR (PÚBLICO)": "OPERATOR NAME (PUBLIC)",
  "ESPECIALIDAD / TÍTULO DE LIDERAZGO": "SPECIALTY/LEADERSHIP TITLE",
  "Cargando perfil de operador...": "Loading operator profile...",
  "Idiomas que Hablas": "Languages ​​you speak",
  "FOTO DE PERFIL (URL)": "PROFILE PHOTO (URL)",
  "Tus Especialidades & Logros Numéricos": "Your Specialties & Numerical Achievements",
  "Imágenes de tus Tours (Galería)": "Images of your Tours (Gallery)",
  "Videos de YouTube (Enlaces)": "YouTube Videos (Links)",
  "VIDEO DE FONDO HERO / ACCENT (.MP4 URL)": "HERO/ACCENT BACKGROUND VIDEO (.MP4 URL)",
  "Galería y Videos Promocionales": "Gallery and Promotional Videos",
  "IMAGEN DE PORTADA / BANNER (URL)": "COVER IMAGE / BANNER (URL)",
  "Selecciona los temas en los que destacas y añade estadísticas para tu perfil público.": "Select the topics you excel in and add statistics for your public profile.",
  "BIOGRAFÍA Y FILOSOFÍA DE SERVICIO (Rich Text / HTML)": "BIOGRAPHY AND PHILOSOPHY OF SERVICE (Rich Text / HTML)",
  "SUFIJO": "SUFFIX",
  "RATING": "RATING",
  "Métricas de Rendimiento (Contadores)": "Performance Metrics (Counters)",
  "Testimonios Específicos del Operador": "Operator Specific Testimonials",
  "Añadir Estadística": "Add Statistics",
  "TEXTO / ETIQUETA": "TEXT/LABEL",
  "Crear Testimonio": "Create Testimonial",
  "VALOR (NÚMERO)": "VALUE (NUMBER)",
  "CLIENTE NOMBRE": "CUSTOMER NAME",
  "Tags de Especialidades": "Specialties Tags",
  "Añadir Acreditación": "Add Accreditation",
  "VÍNCULO FACEBOOK (URL)": "FACEBOOK LINK (URL)",
  "NOMBRE CERTIFICADO": "CERTIFIED NAME",
  "EMISOR / ESCUELA": "ISSUER / SCHOOL",
  "VÍNCULO INSTAGRAM (URL)": "INSTAGRAM LINK (URL)",
  "Agregar Testimonio": "Add Testimonial",
  "VÍNCULO TIKTOK (URL)": "TIKTOK LINK (URL)",
  "Redes Sociales y Enlaces Corporativos": "Social Networks and Corporate Links",
  "Certificaciones y Licencias Oficiales": "Official Certifications and Licenses",
  "Añadir Licencia / Diploma": "Add License/Diploma",
  "Define en qué orden aparecerán las secciones en tu página pública. Arrastra o usa las flechas para reordenar los bloques de contenido.": "Define in what order the sections will appear on your public page. Drag or use the arrows to reorder content blocks.",
  "Ej: Guía de Yates de Lujo & Biólogo Marino": "Ex: Luxury Yacht Guide & Marine Biologist",
  "Optimización para Google y Buscadores (SEO)": "Optimization for Google and Search Engines (SEO)",
  "KEYWORDS (PALABRAS CLAVE GOOGLE)": "KEYWORDS (GOOGLE KEYWORDS)",
  "WHATSAPP VÍNCULO DIRECTO (URL O NÚMERO)": "WHATSAPP DIRECT LINK (URL OR NUMBER)",
  "Orden de Secciones Públicas": "Order of Public Sections",
  "SITIO WEB PERSONAL / PORTAFOLIO (URL)": "PERSONAL WEBSITE / PORTFOLIO (URL)",
  "SEO FRIENDLY SLUG (🔒 Protegido)": "SEO FRIENDLY SLUG (🔒 Protected)",
  "Ej: Cancún, Quintana Roo": "Ex: Cancun, Quintana Roo",
  "VÍNCULO CANAL YOUTUBE (URL)": "YOUTUBE CHANNEL LINK (URL)",
  "Ej: Cruz Roja": "Ex: Red Cross",
  "Ej: Tours": "Ex: Tours",
  "Ej: 350": "Ex: 350",
  "Ej: +": "Ex: +",
  "Ej: Primeros Auxilios": "Ex: First Aid",
  "Pegar URL de foto...": "Paste photo URL...",
  "Ej: 2022": "Ex: 2022",
  "Ej: Francés": "Ex: French",
  "https://www.youtube.com/watch?v=...": "https://www.youtube.com/watch?v=...",
  "Excelente guía, muy profesional...": "Excellent guide, very professional...",
  "Categoría": "Category",
  "https://tuweb.com": "https://tuweb.com",
  "Estado/Provincia": "State/Province",
  "Gestión de Aeropuertos": "Airport Management",
  "Tiempo Recomendado": "Recommended Time",
  "https://youtube.com/@tu_canal": "https://youtube.com/@tu_canal",
  "https://facebook.com/tu_pagina": "https://facebook.com/tu_pagina",
  "https://tiktok.com/@tu_usuario": "https://tiktok.com/@your_user",
  "https://instagram.com/tu_usuario": "https://instagram.com/your_user",
  "https://wa.me/529981234567": "https://wa.me/529981234567",
  "Nueva Actividad": "New Activity",
  "Subir": "Increase",
  "Gestión de atracciones turísticas y actividades VIP.": "Management of tourist attractions and VIP activities.",
  "Descripción Larga": "Long Description",
  "Descripción detallada": "Detailed description",
  "Ej: Eco-Arqueológico": "Ex: Eco-Archaeological",
  "Galería de Fotos": "Photo Gallery",
  "Ej: 4 Horas": "Ex: 4 Hours",
  "Experiencias & Tours": "Experiences & Tours",
  "Sincronizando aventuras...": "Synchronizing adventures...",
  "Muy Alta": "Very High",
  "Alta": "High",
  "Baja": "Low",
  "USD": "USD",
  "Popularidad": "Popularity",
  "Media": "Average",
  "Tipo": "Guy",
  "Cargando aventuras...": "Loading adventures...",
  "Nombre de la Playa": "Beach Name",
  "Actividad / Tipo": "Activity/Type",
  "PayPal": "PayPal",
  "Clave Secreta (Secret Key)": "Secret Key",
  "Clave Pública (Public Key)": "Public Key",
  "Descripción detallada de la playa": "Detailed description of the beach",
  "Configuración de Facturación": "Billing Settings",
  "Cargando configuración...": "Loading configuration...",
  "Ej: Pública, Privada, Parque": "Ex: Public, Private, Park",
  "Stripe": "Stripe",
  "Acepta tarjetas de crédito y débito globalmente.": "Accepts credit and debit cards globally.",
  "Vincula tus pasarelas de pago para recibir el dinero de las reservas directamente en tus cuentas.": "Link your payment gateways to receive money from reservations directly into your accounts.",
  "Sincronizando catálogo...": "Synchronizing catalog...",
  "Pega tu Client ID aquí...": "Paste your Client ID here...",
  "Pega tu Secret Key aquí...": "Paste your Secret Key here...",
  "VAMOS JUNTOS • LUXURY TRAVEL": "LET'S GO TOGETHER • LUXURY TRAVEL",
  "Permite pagos con cuenta PayPal o tarjeta.": "Allows payments with PayPal account or card.",
  "sk_live_...": "sk_live_...",
  "PREVIEW EXCLUSIVO": "EXCLUSIVE PREVIEW",
  "pk_live_...": "pk_live_...",
  "Secret Key": "Secret Key",
  "Client ID": "Client ID",
  "VAMOS JUNTOS": "LET'S GO TOGETHER",
  "PRECIO TOTAL": "TOTAL PRICE",
  "Imagen de Portada": "Cover Image",
  "CHOFER ASIGNADO": "ASSIGNED DRIVER",
  "Package Builder": "Package Builder",
  "Nombre del Paquete": "Package Name",
  "ITINERARIO SELECTO": "SELECTED ITINERARY",
  "Diseña experiencias únicas compuestas por múltiples servicios": "Design unique experiences composed of multiple services",
  "Reserva con tu Concierge VIP": "Book with your VIP Concierge",
  "No se han añadido servicios aún.": "No services have been added yet.",
  "Precio Total": "Total Price",
  "Vista Previa": "Preview",
  "Hora de Salida (Default)": "Departure Time (Default)",
  "Seleccionar Chofer / Taxi": "Select Driver / Taxi",
  "Gestiona la secuencia de servicios": "Manage the sequence of services",
  "🚖 Seleccionar Chofer": "🚖 Select Driver",
  "Itinerario del Paquete": "Package Itinerary",
  "Asignar Chofer (Taxi)": "Assign Driver (Taxi)",
  "Selecciona una categoría arriba para empezar a construir": "Select a category above to start building",
  "No hay taxis/choferes disponibles en la base de datos": "There are no taxis/drivers available in the database",
  "Cancelado": "Canceled",
  "Confirmado": "Confirmed",
  "Gestión de todas las reservaciones de hospedaje.": "Management of all lodging reservations.",
  "Hotel / Habitación": "Hotel/Room",
  "Detalla qué incluye este paquete...": "Details what this package includes...",
  "Ej: Luxury Cancun Experience": "Ex: Luxury Cancun Experience",
  "Reservas de Hoteles": "Hotel Reservations",
  "Check-in Hoy": "Check-in Today",
  "Confirmar Selección": "Confirm Selection",
  "Check-in / Check-out": "Check-in / Check-out",
  "Hotel": "Hotel",
  "Estándar": "Standard",
  "Datos Generales": "General Data",
  "Boutique": "Boutique",
  "Nombre del Hotel": "Hotel Name",
  "Gestión de Hoteles": "Hotel Management",
  "Resort": "Resort",
  "Administra tu portafolio de alojamientos y habitaciones.": "Manage your portfolio of accommodations and rooms.",
  "Buscar por cliente, email u hotel...": "Search by client, email or hotel...",
  "Comienza agregando tu primer alojamiento.": "Start by adding your first accommodation.",
  "Cabañas": "Cabins",
  "Ubicación y Contacto": "Location and Contact",
  "Hostal": "Hostel",
  "Mantenimiento": "Maintenance",
  "Cerrado": "Closed",
  "Dirección Exacta": "Exact Address",
  "Estrellas (1-5)": "Stars (1-5)",
  "Descripción Completa": "Full Description",
  "Estado / Región": "State/Region",
  "Coordenadas (Lat, Lng)": "Coordinates (Lat, Lng)",
  "Ver en el mapa": "View on map",
  "Check-In": "Check-In",
  "Añadir Habitación": "Add Room",
  "Políticas del Hotel": "Hotel Policies",
  "Check-Out": "Check-Out",
  "Políticas y Horarios": "Policies and Schedules",
  "Email Contacto": "Email Contact",
  "Sin habitaciones": "No rooms",
  "No fumar, se admiten mascotas...": "No smoking, pets allowed...",
  "Gestiona el inventario y precios por noche.": "Manage inventory and prices per night.",
  "Admin": "Admin",
  "Inactiva": "Inactive",
  "Política de Cancelación": "Cancellation Policy",
  "/ noche": "/ evening",
  "Cerrar Sesión": "Sign Out",
  "Inventario (Cantidad disponible)": "Inventory (Available quantity)",
  "Capacidad Máxima (Personas)": "Maximum Capacity (People)",
  "Tipo (Ej. Suite con vista al mar)": "Type (e.g. Suite with sea view)",
  "Agrega tipos de habitación para que puedan reservar.": "Add room types so they can book.",
  "Precio Base (por Noche)": "Base Price (per night)",
  "ESCANEA AQUÍ": "SCAN HERE",
  "Paquetes Premium": "Premium Packages",
  "Este paquete es promocional directo.": "This package is direct promotional.",
  "Gestiona el catálogo de experiencias exclusivas disponibles para todos los clientes.": "Manage the catalog of exclusive experiences available to all clients.",
  "Nuevo Paquete": "New Package",
  "Descargar Sticker QR": "Download Sticker QR",
  "Luxury Travel Experience": "Luxury Travel Experience",
  "Driver VIP •": "VIP Driver •",
  "Cargando paquetes...": "Loading packages...",
  "PAQUETE EXCLUSIVO": "EXCLUSIVE PACKAGE",
  "Ver Detalles": "See Details",
  ", // nuevos clientes\r\n  conversion:": ", // new clients\r\n  conversion:",
  ", // reservas hoy\r\n  newClients:": ", // reservations today\r\n  newClients:",
  "Generar QR Marketing": "Generate QR Marketing",
  ", // reservas\r\n  totalRevenue:": ", // reservations\r\n  totalRevenue:",
  "Confirmar Solicitud": "Confirm Request",
  ", // ingresos\r\n  reservationsToday:": ", // income\r\n  reservationsToday:",
  ", // tasa conversión\r\n  availableServices:": ", // conversion rate\r\n  availableServices:",
  "No hay paquetes premium registrados": "No premium packages registered",
  "Los nuevos paquetes aparecerán aquí.": "New packages will appear here.",
  "0 ? '#10b981' : trend": "0 ? '#10b981' : trend",
  ", // servicios ocupados\r\n  cancelations:": ", // services busy\r\n  cancellations:",
  ", // ticket promedio\r\n  topDest:": ", // average ticket\r\n  topDest:",
  ", // conductor top\r\n  topYacht:": ", // top driver\r\n  topYacht:",
  ", // servicios disponibles\r\n  occupiedServices:": ", // available services\r\n  occupiedServices:",
  ", // yate top\r\n  topRestaurant:": ", // yacht top\r\n  topRestaurant:",
  ": trend": ": trend",
  ", // cancelaciones\r\n  ticketPromedio:": ", // cancellations\r\n  average ticket:",
  ", // destino top\r\n  topDriver:": ", // top destination\r\n  topDriver:",
  "Fecha Creación": "Creation Date",
  "Reembolsada": "Refunded",
  "Cotización": "Price",
  "Todos": "All",
  "Todas": "All",
  "En curso": "In progress",
  "Finalizada": "Finished",
  "Agencia": "Agency",
  "Viajes Cancún SA": "Cancun Travel SA",
  "Parcialmente pagada": "Partially paid",
  "Caribe Tours": "Caribbean Tours",
  "Carlos Gómez": "Carlos Gomez",
  "Sofía Castro": "Sofia Castro",
  "Elena Ruiz": "Elena Ruiz",
  "Roberto Díaz": "Roberto Diaz",
  "Asesor": "Adviser",
  "Sistema Auto": "Auto System",
  "Directo Cliente": "Direct Customer",
  "Agencia Expedia": "Expedia Agency",
  "Directo Web": "Web Direct",
  "Mundo VIP": "VIP World",
  "WhatsApp": "WhatsApp",
  "Sitio Web": "Website",
  "Isla Mujeres": "Isla Mujeres",
  "Playa del Carmen": "Playa del Carmen",
  "Llamada": "Call",
  "Cancún": "Cancun",
  "Destino": "Destination",
  "Cozumel": "Cozumel",
  "Tulum": "Tulum",
  "Canal de Venta": "Sales Channel",
  "Vendidos:": "Sold:",
  "Instagram": "instagram",
  "Ficha Completa de Reserva": "Complete Reservation Sheet",
  "Bloq:": "Block:",
  "Valor Mín / Máx": "Min/Max Value",
  "Agencia Afiliada": "Affiliated Agency",
  "Ninguna reserva coincide con los filtros aplicados.": "No reservation matches the applied filters.",
  "Ocupación de cupos": "Occupation of quotas",
  "Libres:": "Free:",
  "Ver Ficha": "See File",
  "Consecutivo": "Consecutive",
  "Fecha de Creación": "Creation Date",
  "Estado Documental": "Documentary Status",
  "2. Cliente & Pasajeros": "2. Client & Passengers",
  "1. Estado & Identificación": "1. Status & Identification",
  "Desglose Pax": "Pax Breakdown",
  "Cliente Principal": "Main Client",
  "Pasajeros Totales": "Total Passengers",
  "3. Destino & Servicios": "3. Destination & Services",
  "Paquete Contratado": "Contracted Package",
  "Fecha de Viaje": "Travel Date",
  "Método de Pago": "Payment Method",
  "Valor Bruto": "Gross Value",
  "Transporte": "Transport",
  "Fecha de Regreso": "Return Date",
  "Impuestos (16%)": "Taxes (16%)",
  "Comisión Asesor (10%)": "Advisory Commission (10%)",
  "Total Cobrado": "Total Collected",
  "Saldo Pendiente": "Outstanding Balance",
  "4. Desglose Financiero": "4. Financial Breakdown",
  "Max": "Max",
  "Min": "min",
  "Código:": "Code:",
  "Flujo de Caja Proyectado": "Projected Cash Flow",
  "Agencia Asociada": "Associated Agency",
  "Confirmación Proveedores": "Supplier Confirmation",
  "Valor Económico Retenido en Cada Estado (USD)": "Economic Value Retained in Each State (USD)",
  "Usuario Creador": "Creator User",
  "5. Operaciones & Auditoría": "5. Operations & Audit",
  "Observaciones Internas": "Internal Observations",
  "Reportes Financieros": "Financial Reports",
  "Cuentas por Cobrar — Aging": "Accounts Receivable — Aging",
  "Ranking de Destinos Más Vendidos": "Ranking of Best-Selling Destinations",
  "Mapa de Calor & Concentración Geográfica": "Heat Map & Geographic Concentration",
  "Distribución por Categoría": "Distribution by Category",
  "Detalle por Destino — Pasajeros, Cancelaciones y Temporadas": "Detail by Destination — Passengers, Cancellations and Seasons",
  "Ocupación Detallada de Cupos por Servicio": "Detailed Occupancy of Spaces by Service",
  "Rentabilidad por Destino": "Profitability by Destination",
  "Ingresos vs Ganancias": "Revenue vs Profits",
  "Control total de ingresos, cuentas por cobrar, rentabilidad y flujo de caja": "Full control of income, accounts receivable, profitability and cash flow",
  "Origen por País": "Origin by Country",
  "Leads vs Ventas Cerradas": "Leads vs Closed Sales",
  "Reportes de Clientes": "Client Reports",
  "Satisfacción del Cliente (NPS por Área)": "Customer Satisfaction (NPS by Area)",
  "Clasificación de Clientes": "Customer Classification",
  "Reportes de Ventas": "Sales Reports",
  "Nuevos Clientes y Tasa de Retorno": "New Clients and Return Rate",
  "Top Clientes por Gasto Acumulado": "Top Clients by Accumulated Spending",
  "Desempeño de asesores, embudo comercial y análisis de cotizaciones": "Advisor performance, trading funnel and quote analysis",
  "Historial, fidelización, satisfacción y comportamiento turístico": "History, loyalty, satisfaction and tourist behavior",
  "Incidencias Operativas": "Operational Incidents",
  "Distribución de Reservas por Hora": "Distribution of Reservations by Hour",
  "Ranking de Asesores / Conductores": "Ranking of Advisors / Drivers",
  "Check-in / Check-out por Hora": "Check-in / Check-out by Hour",
  "Embudo Comercial (Funnel)": "Commercial Funnel",
  "Desempeño, pagos y cumplimiento SLA de aliados comerciales": "Performance, payments and SLA compliance of business partners",
  "Desempeño de Proveedores — Puntualidad y Calificación": "Supplier Performance — Punctuality and Qualification",
  "Check-in/out, itinerarios, incidencias y flujo de viajeros": "Check-in/out, itineraries, incidents and traveler flow",
  "Reportes Operativos": "Operational Reports",
  "Reportes de Proveedores": "Supplier Reports",
  "Análisis de ocupación, ranking geográfico y tendencias por destino": "Analysis of occupancy, geographic ranking and trends by destination",
  "Campañas, origen de clientes, CAC y ROI por canal": "Campaigns, customer origin, CAC and ROI by channel",
  "Reportes de Destinos": "Destination Reports",
  "Campañas Activas — Performance": "Active Campaigns — Performance",
  "Flujo de Pagos a Proveedores": "Flow of Payments to Suppliers",
  "Leads por Canal y Período": "Leads by Channel and Period",
  "Reportes de Marketing": "Marketing Reports",
  "Distribución de Tráfico": "Traffic Distribution",
  "Mapa Interactivo de Calor": "Interactive Heat Map",
  "Detalle de Proveedores": "Supplier Detail",
  "Alertas Predictivas": "Predictive Alerts",
  "Dashboard ejecutivo, predicciones de demanda y comparativos históricos": "Executive dashboard, demand predictions and historical comparisons",
  "Comparativo de Períodos": "Comparison of Periods",
  "Ranking de Destinos": "Destination Ranking",
  "Actividad de usuarios, trazabilidad y alertas críticas del sistema": "User activity, traceability and critical system alerts",
  "Forecast vs Real — Proyección de Demanda": "Forecast vs Real — Demand Projection",
  "Reportes Administrativos & Auditoría": "Administrative Reports & Audit",
  "🚨 Alertas Críticas del Sistema": "🚨Critical System Alerts",
  "Dashboard Ejecutivo & BI Estratégico": "Executive Dashboard & Strategic BI",
  "Tendencia Semanal por Destino": "Weekly Trend by Destination",
  "Reservas:": "Reservations:",
  "Tendencia:": "Trend:",
  "Ingresos:": "Income:",
  "Actualizar datos": "Update data",
  "Mapa de Calor Turístico": "Tourist Heat Map",
  "No hay datos suficientes": "There is not enough data",
  "Actividad del Sistema": "System Activity",
  "Zonas calientes con mayor volumen de reservas en la Riviera Maya.": "Hot areas with the highest volume of reserves in the Riviera Maya.",
  "Pasa el cursor sobre los círculos del mapa para explorar el desglose geográfico en tiempo real.": "Hover over the circles on the map to explore the geographic breakdown in real time.",
  "Log de Auditoría en Tiempo Real": "Real Time Audit Log",
  "Copiar": "Copy",
  "Inicio:": "Start:",
  "No se encontraron registros de auditoría que coincidan.": "No matching audit records were found.",
  "Buscar en logs...": "Search logs...",
  "ITINERARIO SOLICITADO": "REQUESTED ITINERARY",
  "SOLICITUD DE CLIENTE": "CUSTOMER REQUEST",
  "Ranking de Zonas": "Zone Ranking",
  "Consola del Sistema e Historial": "System Console and History",
  "VAMOS JUNTOS • CUSTOM REQUEST": "LET'S GO TOGETHER • CUSTOM REQUEST",
  "No hay servicios en el itinerario.": "There are no services on the itinerary.",
  "PRESUPUESTO": "BUDGET",
  "Asignar": "Assign",
  "• \r\n                                                    Vence:": "• \r\n                                                    Expires:",
  "Licencia:": "License:",
  "SOLICITUD": "APPLICATION",
  "Solicitudes de Clientes": "Customer Requests",
  "Vamos Juntos Luxury": "Let's go together Luxury",
  "Asignar Chófer": "Assign Driver",
  "Gestión y confirmación de paquetes personalizados creados por los clientes.": "Management and confirmation of custom packages created by clients.",
  "No se encontraron chóferes.": "No drivers were found.",
  "Presupuesto": "Budget",
  "No hay solicitudes pendientes": "There are no pending requests",
  "Las nuevas solicitudes aparecerán aquí automáticamente.": "New requests will appear here automatically.",
  "Ver Itinerario": "See Itinerary",
  "Directorio Gastronómico": "Gastronomic Directory",
  "Itinerario (Preview)": "Itinerary (Preview)",
  "Solicitud / Fecha": "Request/Date",
  "Presupuesto Estimado": "Estimated Budget",
  "Cargando solicitudes...": "Loading requests...",
  "Buscar por nombre, modelo o placa...": "Search by name, model or license plate...",
  "Ver Ubicación Gourmet": "See Gourmet Location",
  "Buscando mesas...": "Looking for tables...",
  "Rango Precio": "Price Range",
  "🔐 Admin Reportes": "🔐 Admin Reports",
  "Restaurante / Cocina": "Restaurant / Kitchen",
  "Nuevo Restaurante": "New Restaurant",
  "Exportar Auditoría (CSV)": "Export Audit (CSV)",
  "Compilando reportes y trazas de auditoría...": "Compiling reports and audit trails...",
  "Auditoría general, trazabilidad, seguridad técnica y monitoreo preventivo de operaciones críticas.": "General audit, traceability, technical security and preventive monitoring of critical operations.",
  "Gestión de restaurantes, bares y experiencias culinarias.": "Management of restaurants, bars and culinary experiences.",
  "AUDITORIA": "AUDIT",
  "PAQUETES": "PACKAGES",
  "SEGURIDAD": "SECURITY",
  "USUARIOS": "USERS",
  "RESERVAS": "RESERVATIONS",
  "AUTH": "AUTH",
  "Registro de Auditoría General": "General Audit Record",
  "Listado completo de todas las transacciones y operaciones ejecutadas.": "Complete list of all transactions and operations executed.",
  "Ningún registro de auditoría coincide con los filtros.": "No audit records match the filters.",
  "Módulo: Todos": "Module: All",
  "Sin datos": "No data",
  "Inspeccionar": "Inspect",
  "CRÍTICO": "CRITICAL",
  "No se han registrado cambios críticos recientes.": "No recent critical changes have been recorded.",
  "Análisis granular de módulos, accesos diarios e interacciones por cuenta.": "Granular analysis of modules, daily accesses and interactions by account.",
  "Auditoría rigurosa de variaciones en tarifas, comisiones, cupones y roles.": "Rigorous audit of variations in rates, commissions, coupons and roles.",
  "Comportamiento e Interacción de Usuarios": "User Behavior and Interaction",
  "Resumen de Actividad por Cuenta": "Activity Summary by Account",
  "Historial de Modificaciones Críticas": "Critical Modification History",
  "Módulos Más Utilizados (Operaciones)": "Most Used Modules (Operations)",
  "Dispositivo": "Device",
  "Fiscalización de transacciones críticas como reembolsos de cobros, comisiones asignadas y pasarelas de pago.": "Supervision of critical transactions such as collection refunds, assigned commissions and payment gateways.",
  "Monitoreo de inicios de sesión fallidos, ubicaciones de red sospechosas y tipos de dispositivos.": "Monitoring for failed logins, suspicious network locations, and device types.",
  "Accesos Recientes e Intentos sospechosos": "Recent Accesses and Suspicious Attempts",
  "Control de Autenticación y Accesos": "Authentication and Access Control",
  "Auditoría de Operaciones Financieras": "Financial Operations Audit",
  "Distribución de Dispositivos": "Device Distribution",
  "IP / Ubicación": "IP/Location",
  "Comparar Diffs": "Compare Diffs",
  "Pagos Procesados (Prisma)": "Processed Payments (Prisma)",
  "$1,200 USD": "$1,200 USD",
  "Trazabilidad de Paquetes Turísticos": "Traceability of Tourist Packages",
  "Historial Visual de la Reserva": "Reservation Visual History",
  "Trazabilidad visual paso a paso de los estados y modificaciones críticas de una reserva.": "Step-by-step visual traceability of the status and critical modifications of a reservation.",
  "Registro estricto de variaciones en cupos de excursiones, inclusiones de tours e itinerarios críticos.": "Strict registration of variations in excursion quotas, tour inclusions and critical itineraries.",
  "$2,850 USD": "$2,850 USD",
  "Reembolsos Autorizados": "Authorized Refunds",
  "Trazabilidad de Pasarela de Pagos (Simulado Stripe / PayPal)": "Payment Gateway Traceability (Simulated Stripe / PayPal)",
  "$48,900 USD": "$48,900 USD",
  "Ajustes Manuales Administrativos": "Administrative Manual Settings",
  "Resuelto": "Resolved",
  "Ningún incidente o bloqueo preventivo activo.": "No incident or preventive block active.",
  "Monitoreo Técnico y Logs del Sistema": "Technical Monitoring and System Logs",
  "Centro de Control de Incidentes y Alertas": "Incident and Alert Control Center",
  "Acciones de Administradores": "Administrator Actions",
  "No se registran acciones administrativas sobre usuarios recientemente.": "No administrative actions on users are recorded recently.",
  "Historial completo de creación/eliminación de usuarios, bloqueos o reajustes de credenciales.": "Complete history of user creation/deletion, blocking or credential resets.",
  "Alertas preventivas auto-detectadas por el motor inteligente de comportamiento sospechoso.": "Preventive alerts auto-detected by the intelligent engine of suspicious behavior.",
  "Monitoreo de latencia, fallos de API y consola interactiva de depuración en tiempo real.": "Real-time latency monitoring, API failures and interactive debugging console.",
  "Marcar Resuelto": "Mark Solved",
  "Carga Memoria": "Memory Load",
  "VALOR NUEVO (AFTER)": "NEW VALUE (AFTER)",
  "Carga CPU": "CPU load",
  "FAILURES MONITORED": "FAILURES MONITORED",
  "Latencia Promedio y Tiempos de Respuesta (ms)": "Average Latency and Response Times (ms)",
  "CONSOLA DE DIAGNÓSTICO DEL SISTEMA v1.0.0": "SYSTEM DIAGNOSTIC CONSOLE v1.0.0",
  "VALOR ANTERIOR (BEFORE)": "PREVIOUS VALUE (BEFORE)",
  "Sockets Activos": "Active Sockets",
  "Pool Database": "Pool Database",
  "OF-LINE": "OFF-LINE",
  "Chofer": "Driver",
  "Amenidades": "Amenities",
  "Sincronizando flota...": "Synchronizing fleet...",
  "Cerrar Inspector": "Close Inspector",
  "Buscar usuario o detalle...": "Search user or detail...",
  "Nuevo Vehículo": "New Vehicle",
  "Vehículo / Placa": "Vehicle / License Plate",
  "Gestión de Flota (VIP)": "Fleet Management (VIP)",
  "Código de Reserva (e.g. RV-2026-0012)": "Reservation Code (e.g. RV-2026-0012)",
  "Control de vehículos, servicios y perfiles de choferes.": "Control of vehicles, services and driver profiles.",
  "Licencia": "License",
  "MATRÍCULA": "TUITION",
  "Detalles": "Details",
  "Perfil": "Profile",
  "Cerrar Ficha": "Close File",
  "Expira": "Expires",
  "VIP SERVICE 24/7": "VIP SERVICE 24/7",
  "ESCANEA Y RESERVA": "SCAN AND RESERVE",
  "PREMIUM TRANSPORT": "PREMIUM TRANSPORT",
  "ID Chofer": "Driver ID",
  "AUDITOR": "AUDITOR",
  "ADMIN": "ADMIN",
  "OPERATOR": "OPERATOR",
  "Rol: Todos": "Role: Everyone",
  "SUPER_ADMIN": "SUPER_ADMIN",
  "Generar QR Sticker": "Generate QR Sticker",
  "Refrescar Lista": "Refresh List",
  "Administración global de perfiles, asignación de roles, bloqueos preventivos y envío de advertencias disciplinarias.": "Global profile management, role assignment, preventive blocking and sending of disciplinary warnings.",
  "👥 Gestión de Usuarios": "👥 User Management",
  "Descargar Sticker QR para Taxi": "Download QR Sticker for Taxi",
  "Gestionar": "Manage",
  "REVISION": "REVISION",
  "BLOQUEADO": "LOCKED",
  "ACTIVO": "ASSET",
  "SUSPENDIDO": "SUSPENDED",
  "Estado: Todos": "Status: All",
  "USER": "USER",
  "Ningún usuario coincide con los filtros aplicados.": "No user matches the applied filters.",
  "Ningún usuario coincide con los filtros.": "No users match the filters.",
  "Cargando usuarios...": "Loading users...",
  "Correo Electrónico:": "Email:",
  "Identificador:": "Identifier:",
  "Nombre Completo:": "Full Name:",
  "Cambiar Rol Operativo": "Change Operational Role",
  "Gestionar Perfil": "Manage Profile",
  "AUDITOR (Auditor Global)": "AUDITOR (Global Auditor)",
  "Ficha de Control Administrativo": "Administrative Control Sheet",
  "OPERATOR (Operador Flotas/Reservas)": "OPERATOR (Fleet/Reserves Operator)",
  "Gestionando cuenta de:": "Managing account of:",
  "USER (Cliente Regular)": "USER (Regular Customer)",
  "Motivo: Fraude": "Reason: Fraud",
  "Uso indebido": "Misuse",
  "Motivo: Spam": "Reason: Spam",
  "ACTIVO (Acceso Normal)": "ACTIVE (Normal Access)",
  "BLOQUEADO (Bloqueo Total)": "LOCKED (Total Block)",
  "SUPER_ADMIN (Super Administrador)": "SUPER_ADMIN (Super Administrator)",
  "Estados de Bloqueo y Suspensiones": "Blocking States and Suspensions",
  "REVISION (Bajo Inspección)": "REVIEW (Under Inspection)",
  "SUSPENDIDO (Bloqueo Temporal)": "SUSPENDED (Temporary Blocking)",
  "ADMIN (Administrador de Sistema)": "ADMIN (System Administrator)",
  "Actualizar Estado de Cuenta": "Update Account Status",
  "Severidad: Informativo (Azul)": "Severity: Informational (Blue)",
  "Redactar Nota Push / Advertencia Directa": "Write Push Note / Direct Warning",
  "Severidad: Advertencia (Amarillo)": "Severity: Warning (Yellow)",
  "Severidad: Crítico (Rojo)": "Severity: Critical (Red)",
  "Severidad: Riesgo (Naranja)": "Severity: Risk (Orange)",
  "Otro Motivo": "Another reason",
  "Manipulación de datos": "Data manipulation",
  "Accesos sospechosos": "Suspicious access",
  "Popup simple al entrar": "Simple popup upon entry",
  "Buscar por usuario, nombre o email...": "Search by user, name or email...",
  "Persistente hasta lectura": "Persistent until read",
  "📜 Bitácora Disciplinaria": "📜 Disciplinary Log",
  "Sin antecedentes disciplinarios en el sistema.": "No disciplinary history in the system.",
  "Especifique el motivo de la suspensión...": "Specify the reason for the suspension...",
  "Popup obligatorio confirmación": "Mandatory confirmation popup",
  "Eliminación Lógica": "Logical Elimination",
  "Eliminación Física": "Physical Elimination",
  "Cargando bitácora...": "Loading log...",
  "Enviar Advertencia Push": "Send Push Warning",
  "Tripulación": "Crew",
  "Registrar Yate": "Register Yacht",
  "Embarcación / Eslora": "Boat / Length",
  "Flota de Yates (Elite)": "Yacht Fleet (Elite)",
  "Tarifa Diaria": "Daily Rate",
  "Zarpando...": "Setting sail...",
  "Sincronizando flota elite...": "Synchronizing elite fleet...",
  "Título del popup (ej: Advertencia Masiva)": "Popup title (ex: Mass Warning)",
  "Mensaje descriptivo de la advertencia disciplinaria...": "Descriptive message of the disciplinary warning...",
  "Gestión de embarcaciones de lujo y tripulaciones.": "Management of luxury vessels and crews.",
  "Marca": "Brand",
  "Tarifa Diaria (USD)": "Daily Rate (USD)",
  "Nombre del Yate": "Yacht Name",
  "Cerrar Lista": "Close List",
  "Exp:": "Exp:",
  "Capacidad (Pasajeros)": "Capacity (Passengers)",
  "Tarifa Día": "Day Rate",
  "Personal a bordo calificado": "Qualified onboard personnel",
  "Detalles de la embarcación, amenidades, etc.": "Details of the boat, amenities, etc.",
  "Eslora (Ej: 60ft)": "Length (Ex: 60ft)",
  "Descargar Plantilla Excel": "Download Excel Template",
  "Plantilla": "Template",
  "Importar": "Import",
  "El archivo está vacío": "The file is empty",
  "0 importados. Revisa el formato del archivo.": "0 imported. Check the file format.",
  "¡Éxito! Se importaron": "Success! Imported",
  "taxis.": "taxis.",
  "hoteles.": "hotels.",
  "Error:": "Error:",
  "Error al leer el archivo. Verifica el formato.": "Error reading the file. Check the format.",
  "Confirmar Eliminación": "Confirm Deletion",
  "¿Estás seguro de que deseas eliminar el hotel": "Are you sure you want to delete the hotel",
  "Se eliminarán también todas sus habitaciones. Esta acción no se puede deshacer.": "All its rooms will also be deleted. This action cannot be undone.",
  "¿Estás seguro de que deseas eliminar el vehículo placa": "Are you sure you want to delete the vehicle plate",
  "Esta acción no se puede deshacer y no eliminará al chofer asociado, solo al vehículo.": "This action cannot be undone and will not delete the associated driver, only the vehicle.",
  "¿Estás seguro de que deseas eliminar el restaurante": "Are you sure you want to delete the restaurant",
  "Esta acción no se puede deshacer.": "This action cannot be undone.",
  "¿Estás seguro de que deseas eliminar la playa": "Are you sure you want to delete the beach",
  "¿Estás seguro de que deseas eliminar el aeropuerto": "Are you sure you want to delete the airport",
  "¿Estás seguro de que deseas eliminar el yate": "Are you sure you want to delete the yacht",
  "y toda su tripulación asociada? Esta acción no se puede deshacer.": "and all its associated crew? This action cannot be undone.",
  "Guardar Hotel": "Save Hotel",
  "Gestiona terminales aéreas para traslados": "Manage air terminals for transfers"
,
  "aeropuertos.": "airports.",
  "Nuevo Aeropuerto": "New Airport",
  "atracciones.": "attractions.",
  "playas.": "beaches.",
  "Nueva Playa": "New Beach",
  "restaurantes.": "restaurants.",
  "Subiendo foto del conductor...": "Uploading driver photo...",
  "Foto subida": "Photo uploaded",
  "Error al subir": "Error uploading",
  "Error al subir foto": "Error uploading photo",
  "Fotos del vehículo subidas": "Vehicle photos uploaded",
  "Error al subir fotos": "Error uploading photos",
  "No se pudo guardar": "Could not save",
  "Editar Vehículo": "Edit Vehicle",
  "Registrar Nuevo Vehículo": "Register New Vehicle",
  "Placa / Matrícula": "License Plate",
  "Color": "Color",
  "Categoría (Tipo)": "Category (Type)",
  "Maletas": "Luggage",
  "Galería del Vehículo": "Vehicle Gallery",
  "Agregar Fotos": "Add Photos",
  "No hay fotos del vehículo. Sube algunas imágenes para mostrarlas a los clientes.": "No vehicle photos. Upload some images to show them to clients.",
  "Datos del Conductor": "Driver Details",
  "Foto": "Photo",
  "Nombre del Chofer": "Driver Name",
  "Vencimiento de Licencia": "License Expiration",
  "Amenidades Disponibles": "Available Amenities",
  "En Mantenimiento": "In Maintenance",
  "Ocupado": "Occupied",
  "Guardar Cambios": "Save Changes",
  "Registrar Vehículo": "Register Vehicle",
  "yates.": "yachts."
,
  "Gestiona destinos costeros y playas": "Manage coastal destinations and beaches",
  "Gestiona restaurantes y ofertas culinarias": "Manage restaurants and culinary offerings"
};

export const tr = (txt: string): string => {
  const isEn = currentLanguage === 'en';
  if (isEn && adminDictionary[txt]) return adminDictionary[txt];
  return txt;
};

export const setLanguage = (lang: string) => {
  currentLanguage = lang;
};
